# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.21.224056'

RELEASE_GIT_HEAD = '2a59336effd2192381ba42e3e1fd59ae7169c998'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'coletdjnz/yt-dlp-dev'

ORIGIN = 'coletdjnz/yt-dlp-dev'

_pkg_version = '2025.06.21.224056'
