# Autogenerated by devscripts/update-version.py

__version__ = '2025.02.08.224548'

RELEASE_GIT_HEAD = 'b6c3d22decc56b8484de0435aa52948d6a59b217'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'coletdjnz/yt-dlp-dev'

ORIGIN = 'coletdjnz/yt-dlp-dev'

_pkg_version = '2025.02.08.224548'
