# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.06.233112'

RELEASE_GIT_HEAD = 'b314cf20bebf3401e58fdb018a411401f83f58b2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'coletdjnz/yt-dlp-dev@sabr'

ORIGIN = 'coletdjnz/yt-dlp-dev'

_pkg_version = '2026.03.06.233112'
